/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
   //Este comentario es del Release PAE1
	public boolean someLibraryMethod() {
        return true;
    }
}
